sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang-3.8
script:
   - make test CC=gcc-5 CXX=g++-5
   - make test CC=clang CXX=clang++
